### ISSUE TITLE
GLIBCXX not found

### ISSUE THREAD

**Issue by xpnerd** [HendrikMuenster/flexBox_CPP#2]
After default cmake, make and installation I get an error when testing. (in the README.md it should actually say `../source` instead of `../` in the code under the Quick Installation)

What I tried is testing 'exampleConstraint' with `tryCPP = 1` in MatLab. When running I get: `Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more
information, click <a href="matlab:opengl('problems')">here</a>.
Invalid MEX-file '/<usr>/flexBox/flexBox_CPP/build/bin/flexBoxCPP.mexa64':
/<location>/Matlab/R2016b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found
(required by /data/home/opdehoek/flexBox/flexBox_CPP/build/bin/flexBoxCPP.mexa64).`

I am running this on a server, so I am not sure if that has any influence, but again I simply followed the Quick installation and end up with this error..., what did I do wrong?

**Comment by LarsHaalck** [comment]
Hi @xpnerd,
sorry I didn't get a notificaiton for this issue and just saw it. I'm looking into it.

**Comment by LarsHaalck** [comment]
Hi @xpnerd,
I added a workaround to the README of the project. It has something to do with the supported compilers for building MEX-Interfaces (see README for details). If it still doesn't work or you have any further questions, please reopen this issue or add a comment.
